export const imageMap: Record<string, any> = {
  "@/assets/images/package1.jpg": require("@/assets/images/package1.jpg"),
  "@/assets/images/package2.jpg": require("@/assets/images/package2.jpg"),
  "@/assets/images/package3.jpg": require("@/assets/images/package3.jpg"),
  "@/assets/images/package4.jpg": require("@/assets/images/package4.jpg"),
  "@/assets/images/package5.jpg": require("@/assets/images/package5.jpg"),
  "@/assets/images/package6.jpg": require("@/assets/images/package6.jpg"),
  "@/assets/images/package7.jpg": require("@/assets/images/package7.jpg"),
  "@/assets/images/package8.jpg": require("@/assets/images/package8.jpg"),
  "@/assets/images/package9.jpg": require("@/assets/images/package9.jpg"),
  "@/assets/images/package10.jpg": require("@/assets/images/package10.jpg"),
  "@/assets/images/package11.jpg": require("@/assets/images/package11.jpg"),
  "@/assets/images/package12.jpg": require("@/assets/images/package12.jpg"),
  "@/assets/images/package13.jpg": require("@/assets/images/package13.jpg"),
  "@/assets/images/package14.jpg": require("@/assets/images/package14.jpg"),
  "@/assets/images/package15.jpg": require("@/assets/images/package15.jpg"),
  "@/assets/images/package16.jpg": require("@/assets/images/package16.jpg"),
  "@/assets/images/package17.jpg": require("@/assets/images/package17.jpg"),
  "@/assets/images/package18.jpg": require("@/assets/images/package18.jpg"),
  "@/assets/images/package19.jpg": require("@/assets/images/package19.jpg"),
  "@/assets/images/package20.jpg": require("@/assets/images/package20.jpg"),
  "@/assets/images/package21.jpg": require("@/assets/images/package21.jpg"),
  "@/assets/images/package22.jpg": require("@/assets/images/package22.jpg"),
  "@/assets/images/package23.jpg": require("@/assets/images/package23.jpg"),
  "@/assets/images/package24.jpg": require("@/assets/images/package24.jpg"),

  "@/assets/images/event.jpg": require("@/assets/images/event.jpg"),
  "@/assets/images/event2.jpg": require("@/assets/images/event2.jpg"),
  "@/assets/images/event3.jpg": require("@/assets/images/event3.jpg"),

  "@/assets/images/guide1.jpg": require("@/assets/images/guide1.jpg"),
  "@/assets/images/guide2.jpg": require("@/assets/images/guide2.jpg"),
  "@/assets/images/guide3.jpg": require("@/assets/images/guide3.jpg"),

  "@/assets/images/landing1.jpg": require("@/assets/images/landing1.jpg"),
  "@/assets/images/landing2.jpg": require("@/assets/images/landing2.jpg"),
  "@/assets/images/landing3.jpg": require("@/assets/images/landing3.jpg"),
  "@/assets/images/landing4.jpg": require("@/assets/images/landing4.jpg"),

  "@/assets/images/logo.png": require("@/assets/images/logo.png"),

  "@/assets/images/adv-8.jpg": require("@/assets/images/adv-8.jpg"),
  "@/assets/images/adv1.jpg": require("@/assets/images/adv1.jpg"),
  "@/assets/images/adv2.jpg": require("@/assets/images/adv2.jpg"),
  "@/assets/images/adv3.jpg": require("@/assets/images/adv3.jpg"),
  "@/assets/images/adv4.jpg": require("@/assets/images/adv4.jpg"),
  "@/assets/images/adv5.jpg": require("@/assets/images/adv5.jpg"),
  "@/assets/images/adv7.jpg": require("@/assets/images/adv7.jpg"),

  "@/assets/images/airline1.jpg": require("@/assets/images/airline1.jpg"),
  "@/assets/images/airline2.jpg": require("@/assets/images/airline2.jpg"),
  "@/assets/images/airline3.jpg": require("@/assets/images/airline3.jpg"),

  "@/assets/images/bike1.jpg": require("@/assets/images/bike1.jpg"),
  "@/assets/images/bike2.jpg": require("@/assets/images/bike2.jpg"),
  "@/assets/images/car.jpg": require("@/assets/images/car.jpg"),

  "@/assets/images/camel1.jpg": require("@/assets/images/camel1.jpg"),

  "@/assets/images/camping1.jpg": require("@/assets/images/camping1.jpg"),
  "@/assets/images/camping3.jpg": require("@/assets/images/camping3.jpg"),
  "@/assets/images/camping4.jpg": require("@/assets/images/camping4.jpg"),

  "@/assets/images/train1.jpg": require("@/assets/images/train1.jpg"),
  "@/assets/images/train2.jpg": require("@/assets/images/train2.jpg"),
  "@/assets/images/train3.jpg": require("@/assets/images/train3.jpg"),

  "@/assets/images/hotel.jpg": require("@/assets/images/hotel.jpg"),
  "@/assets/images/hotel-1.jpg": require("@/assets/images/hotel-1.jpg"),
  "@/assets/images/hotel-2.jpg": require("@/assets/images/hotel-2.jpg"),

  "@/assets/images/travel1.jpg": require("@/assets/images/travel1.jpg"),
  "@/assets/images/travel2.jpg": require("@/assets/images/travel2.jpg"),
  "@/assets/images/travel3.jpg": require("@/assets/images/travel3.jpg"),

  // Add more as needed

  "@/assets/images/amazon.png": require("@/assets/images/amazon.png"),
  "@/assets/images/flipkart.png": require("@/assets/images/flipkart.png"),
  "@/assets/images/myntra.png": require("@/assets/images/myntra.png"),
  "@/assets/images/ajio.png": require("@/assets/images/ajio.png"),
  "@/assets/images/Rapido.png": require("@/assets/images/Rapido.png"),
  "@/assets/images/zepto.png": require("@/assets/images/zepto.png"),
  "@/assets/images/uber.png": require("@/assets/images/uber.png"),
  "@/assets/images/ola.png": require("@/assets/images/ola.png"),

  "@/assets/images/adventure1.jpg": require("@/assets/images/adventure1.jpg"),
  "@/assets/images/adventure2.jpg": require("@/assets/images/adventure2.jpg"),
  "@/assets/images/adventure3.jpg": require("@/assets/images/adventure3.jpg"),
  "@/assets/images/adventure4.jpg": require("@/assets/images/adventure4.jpg"),
  "@/assets/images/adventure5.jpg": require("@/assets/images/adventure5.jpg"),
  "@/assets/images/adventure6.jpg": require("@/assets/images/adventure6.jpg"),
  "@/assets/images/adventure7.jpg": require("@/assets/images/adventure7.jpg"),
  "@/assets/images/adventure8.jpg": require("@/assets/images/adventure8.jpg"),
  "@/assets/images/adventure9.jpg": require("@/assets/images/adventure9.jpg"),
  "@/assets/images/adventure10.jpg": require("@/assets/images/adventure10.jpg"),
};
